application: contributing
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /s/create
  script: main.py

- url: /s/login
  script: main.py

- url: /s/logout
  script: main.py

- url: /s/openid
  script: consumer.py

- url: /s/startopenid
  script: consumer.py

- url: /s/finish
  script: consumer.py

- url: .*
  script: main.py
