# application: contributing-hrd
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /s/create
  script: main.py

- url: /s/login
  script: main.py

- url: /s/logout
  script: main.py

- url: /s/openid
  script: consumer.py

- url: /s/startopenid
  script: consumer.py

- url: /s/finish
  script: consumer.py

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: .*
  script: main.py
